branch-defaults:
  default:
    environment: AFL-Scheduler-dev
    group_suffix: null
environment-defaults:
  AFL-Scheduler-dev:
    branch: null
    repository: null
global:
  application_name: AFL_Scheduler
  branch: null
  default_ec2_keyname: *****
  default_platform: Python 2.7
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
